// 📁 SendKeysHelper.cs – KORRIGIERT
using System;
using System.Windows.Input;

namespace CouchKeys
{
    public static class SendKeysHelper
    {
        // https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.sendkeys?view=windowsdesktop-8.0#remarks
        public static string MapKeyToSendKeysFormat(Key key)
        {
            return key switch
            {
                Key.Space => " ",
                Key.Enter => "{ENTER}",
                Key.Tab => "{TAB}",
                Key.Escape => "{ESC}",
                Key.Back => "{BACKSPACE}",
                Key.LeftShift => "+",
                Key.RightShift => "+",
                Key.LeftCtrl => "^",
                Key.RightCtrl => "^",
                Key.LeftAlt => "%",
                Key.RightAlt => "%",
                Key.F1 => "{F1}",
                Key.F2 => "{F2}",
                Key.F3 => "{F3}",
                Key.F4 => "{F4}",
                Key.F5 => "{F5}",
                Key.F6 => "{F6}",
                Key.F7 => "{F7}",
                Key.F8 => "{F8}",
                Key.F9 => "{F9}",
                Key.F10 => "{F10}",
                Key.F11 => "{F11}",
                Key.F12 => "{F12}",
                Key.D0 => "0",
                Key.D1 => "1",
                Key.D2 => "2",
                Key.D3 => "3",
                Key.D4 => "4",
                Key.D5 => "5",
                Key.D6 => "6",
                Key.D7 => "7",
                Key.D8 => "8",
                Key.D9 => "9",
                Key.A => "A",
                Key.B => "B",
                Key.C => "C",
                Key.D => "D",
                Key.E => "E",
                Key.F => "F",
                Key.G => "G",
                Key.H => "H",
                Key.I => "I",
                Key.J => "J",
                Key.K => "K",
                Key.L => "L",
                Key.M => "M",
                Key.N => "N",
                Key.O => "O",
                Key.P => "P",
                Key.Q => "Q",
                Key.R => "R",
                Key.S => "S",
                Key.T => "T",
                Key.U => "U",
                Key.V => "V",
                Key.W => "W",
                Key.X => "X",
                Key.Y => "Y",
                Key.Z => "Z",
                Key.Oem1 => ";",
                Key.Oem2 => "/",
                Key.Oem3 => "`",
                Key.Oem4 => "[",
                Key.Oem5 => "\\",
                Key.Oem6 => "]",
                Key.Oem7 => "'",
                Key.OemPeriod => ".",
                Key.OemComma => ",",
                Key.OemMinus => "-",
                Key.OemPlus => "=",
                Key.OemClear => "{CLEAR}",
                Key.NumPad0 => "0",
                Key.NumPad1 => "1",
                Key.NumPad2 => "2",
                Key.NumPad3 => "3",
                Key.NumPad4 => "4",
                Key.NumPad5 => "5",
                Key.NumPad6 => "6",
                Key.NumPad7 => "7",
                Key.NumPad8 => "8",
                Key.NumPad9 => "9",
                Key.Multiply => "*",
                Key.Add => "{+}",
                Key.Separator => ",",
                Key.Subtract => "-",
                Key.Decimal => ".",
                Key.Divide => "/",
                _ => $"{{{key}}}" // fallback (z.B. "{OemBackslash}")
            };
        }
    }
}
